name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        clean: true

    - name: Set up Git
      run: |
        git config --global user.email "venkatareddygirish@gmail.com"
        git config --global user.name "GirishCodeAlchemy"

    - name: Add GitLab remote
      run: git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/GirishCodeAlchemy1/gitlab-testing.git

    - name: Push to GitLab
      run: git push gitlab main
